In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import pandas as pd
import json, os, requests
from api_key import api_key

In [2]:
# ---------------
# Starbucks Data
# ---------------

#read Starbucks csv
starbucks_data_path = os.path.join("Source_Files","Starbucks_US_2018_11_12.csv")
starbucks_data = pd.read_csv(starbucks_data_path)

#pull data from Starbucks csv
clean_data = starbucks_data[['city', 'state', 'zip_code']]

SB_states_data = pd.DataFrame(clean_data.groupby('state')['city'].count())
SB_states_data.rename(columns={'city':'Starbucks Stores'}, inplace=True)

In [3]:
# -------------------
# Dunkin Donuts Data
# -------------------


#read the Dunkin json file
with open('dunkinDonuts.json', 'r') as file:
    results = json.load(file)
    data = results['data']
    
# Create dataframe full of relevant information about Dunkin Donuts stores in the US
# First create empty list for State, Zip code, and whether they have almond milk
states,zips,almond = [],[],[]

#Go item by item in the list, each item is a dictionary
for i in data:
    states.append(i['state'])
    zips.append(i['postal'])
    
    if i['almond']=='Y':
        almond.append(1)
    else:
        almond.append(0)

ddDF = pd.DataFrame({
    'State':states,
    'Zip Code':zips,
    'Almond':almond
})

totalDunkin = len(data)

#Group the dataframe of individual stores into a summary by state
grpbyState = ddDF.groupby('State')

#empty dataframe for the final results
DDtotals = pd.DataFrame()

DDtotals['Dunkin Stores'] = grpbyState.count()['Zip Code']
DDtotals['Dunkins with Almond Milk'] = grpbyState.mean()['Almond']
DDtotals['Dunkins with Almond Milk'] = pd.Series(["{0:.0f}%".format(val * 100) for val in DDtotals['Dunkins with Almond Milk']], index = DDtotals.index)

In [19]:

# ------------
# Income Data
# ------------

# Request data with API key
api_key = api_key
url = "https://api.stlouisfed.org/geofred/shapes/file?"
query_url = f"https://api.stlouisfed.org/geofred/series/data?series_id=WIPCPI&api_key={api_key}&file_type=json&date=2019-01-01"
response = requests.get(query_url)

# Display API call response
data = response.json()
data_2019 = data["meta"]["data"]["2019"]


# Store state names and personal income to list
state, income, state_abv = [], [], []

# Make a for loop to go through the url response to get each state's personal income
for i in data_2019:
    state.append(i["series_id"][0:2])
    income.append(i["value"])

    # Display personal income per capital into dataframe
personal_income_df = pd.DataFrame({"State": state, "Income": income})
personal_income_df.head()


# ----------------
# Population Data
# ----------------

file = "Source_Files/population_by_state_2019.xls"
df = pd.read_excel(file)

population = df[["State", "Population"]]


# -------------------
# Merge Income + Pop
# -------------------

GDPandPOP = pd.merge(population, personal_income_df, how="outer")
GDPandPOP=GDPandPOP.set_index('State')

In [20]:
# ---------------------
# Merge All Dataframes
# ---------------------

# SB_states_data = index of state and one column of total Starbucks Stores in that state
# DDtotals = index of state, columns of total DD stores and % with almond milk
# GDPandPOP = index of state, columns of income and population

stores = pd.merge(SB_states_data,DDtotals, left_index=True, right_index=True)
finalDF = pd.merge(GDPandPOP, stores, left_index=True, right_index=True)
finalDF

,Population,Income,Starbucks Stores,Dunkin Stores,Dunkins with Almond Milk
AL,4907.965,44102.0,88,41,54%
AK,733.603,62629.0,51,2,0%
AZ,7291.843,45975.0,513,96,71%
AR,3020.985,44582.0,61,8,75%
CA,39437.610,66745.0,2968,116,22%
CO,5758.486,61159.0,501,45,56%
CT,3566.022,77273.0,129,524,91%
DE,976.668,54323.0,32,67,12%
DC,708.253,83111.0,91,26,85%
FL,21492.056,52391.0,741,1002,20%
GA,10628.020,48188.0,356,228,64%
HI,1415.615,57026.0,109,12,0%
IL,12667.017,58786.0,627,695,82%
IN,6731.010,48687.0,255,87,61%
IA,3159.596,51791.0,101,33,61%
KS,2912.635,53439.0,108,29,59%
KY,4472.345,43724.0,126,38,18%
LA,4658.285,47363.0,94,14,36%
ME,1345.770,50575.0,29,161,86%
MD,6054.954,64541.0,279,282,76%
MA,6894.883,74161.0,282,1156,92%
MI,9984.795,49238.0,301,85,75%
MN,5640.053,58830.0,204,23,9%
MS,2978.227,38887.0,33,8,38%
MO,6140.475,48631.0,208,48,48%
NE,1932.571,54567.0,64,19,68%
NV,3090.771,50985.0,263,26,81%
NH,1360.783,63452.0,34,220,94%
NJ,8891.258,70399.0,285,892,67%
NM,2099.634,43268.0,88,16,50%
NY,19463.131,71682.0,679,1501,84%
NC,10501.384,47706.0,385,344,1%
OH,11696.507,50167.0,424,211,17%
OK,3960.676,47297.0,78,11,45%
PA,12798.883,58046.0,399,647,19%
RI,1058.158,56426.0,28,175,94%
SC,5157.702,45359.0,159,119,0%
TN,6830.325,48676.0,207,106,63%
TX,28986.794,52829.0,1148,175,54%
UT,3203.383,48978.0,113,7,100%
VT,624.046,55288.0,9,52,92%
VA,8556.642,59509.0,434,263,57%
WV,1795.263,42242.0,31,23,30%
WI,5824.581,53207.0,153,64,70%
WY,580.116,62044.0,22,1,0%

In [2]:
print(finalDF["Population"].max())
#print(finalDF["Population"].min())

NameError: name 'finalDF' is not defined